targets:
  $default:
    builders:
      slang_build_runner:
        options:
          base_locale: en
          fallback_strategy: base_locale
          input_directory: lib/i18n
          input_file_pattern: .i18n.json
          output_directory: lib/i18n
          output_file_name: translations.g.dart
          locale_handling: true
          flutter_integration: true
          translate_var: t
          enum_name: AppLocale
          class_name: Translations
          key_case: snake
          key_map_case: camel
          param_case: camel
          pluralization:
            auto: cardinal
          timestamp: true
          statistics: true
